spring:
  application:
    name: fraudshield-transactional
  datasource:
    url: jdbc:postgresql://localhost:5432/fraudshield
    username: fraudshield
    password: fraudshield
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
